[package]
name = "win_test"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = {version = "0.29.1",features = []}
serde = { version = "1.0.210", features = ["derive"] }
chrono = "0.4.38"
eframe = "0.29.1"